/** 기본 역할 권한(spec/IAM-identity.md Permission 목록 중 M1·M2 화면이 쓰는 것). 가짜 gateway와 화면 렌더 도우미가 함께 쓴다 */
const M2_READ = ["DEV_READ", "TS_READ"];
const M2_OPERATE = [...M2_READ, "DEV_PLACE", "SRC_READ", "SCRIPT_READ", "INGEST_READ", "TS_EXPORT"];
const M2_INTEGRATE = [...M2_OPERATE, "DEV_ADMIN", "SRC_ADMIN", "SCRIPT_WRITE", "INGEST_PAYLOAD_READ", "INGEST_REPROCESS"];
/** M3 폐루프(가상): 플로우(FLW)·가상 환경(SIM)·제어(ACT) 권한 */
const M3_ANALYST = ["FLOW_READ", "SIM_READ", "SIM_RUN"];
const M3_OPERATOR = [...M3_ANALYST, "FLOW_WRITE"];
const M3_INTEGRATOR = [...M3_OPERATOR, "FLOW_DEPLOY_CONTROL", "SIM_MANAGE", "DRIVER_MANAGE", "CAPABILITY_MANAGE"];
const M3_ADMIN = [...M3_INTEGRATOR, "FLOW_APPROVE", "SIM_ADMIN", "CONTROL_SETTINGS"];
/** M4 자동화 완성: 규칙·알람·알림(RUL), 제어 확장(ACT-02·05·06), Sink·Git·확장 노드(FLW-04·11) — spec/IAM-identity.md Permission 목록의 기본 역할 */
const M4_ANALYST = ["RULE_READ"];
const M4_OPERATOR = [...M4_ANALYST, "RULE_WRITE", "ALARM_HANDLE", "NOTIFY_POLICY_WRITE", "SCENE_RUN", "EMERGENCY_STOP", "WORKORDER_WRITE"];
const M4_INTEGRATOR = [...M4_OPERATOR, "SCENE_MANAGE", "SCHEDULE_MANAGE", "INTERLOCK_MANAGE", "EMERGENCY_RELEASE", "SINK_CONNECTION_MANAGE", "GIT_SYNC_MANAGE"];
const M4_ADMIN = [...M4_INTEGRATOR, "NOTIFY_CHANNEL_MANAGE", "NODE_PACKAGE_MANAGE"];
/** M5 데이터 관리: 가져오기·보관 정책(TSD, ADMIN·INTEGRATOR) */
const M5_DATA_INTEGRATOR = ["TS_IMPORT", "TS_POLICY"];
/** M5 대시보드(DSH): 조회는 모두, 편집은 ADMIN·INTEGRATOR·OPERATOR·ANALYST, 브랜딩은 ADMIN(spec/IAM-identity.md) */
const M5_DASH_READ = ["DASHBOARD_READ"];
const M5_DASH_WRITE = [...M5_DASH_READ, "DASHBOARD_WRITE"];
/** M5 scripts: 데이터 품질(UI-ING-06)은 ANALYTICS_READ로도 본다(API-ING-13) */
const M5_ANALYST = ["ANALYTICS_READ"];
/** M6 분석·AI(contracts BuiltinRole): 분석 조회 V+, 실행 A+, AI 사용 모두, API 키·MCP 토큰 발급 A+(VIEWER 제외) */
const M6_VIEWER = ["ANALYTICS_READ", "AI_USE", "ENE_READ"];
const M6_ANALYST = [...M6_VIEWER, "ANALYTICS_RUN", "API_TOKEN_ISSUE"];
export const ADMIN_PERMISSIONS = ["BRANDING_MANAGE", ...M5_DASH_WRITE, ...M5_DATA_INTEGRATOR, "IAM_MANAGE", "AUDIT_READ", "OPS_MANAGE", "ALARM_READ", "DEVICE_CONTROL", "SCRIPT_FORCE_DEPLOY", ...M2_INTEGRATE, ...M3_ADMIN, ...M4_ADMIN, ...M6_ANALYST];
export const INTEGRATOR_PERMISSIONS = [...M5_DASH_WRITE, ...M5_DATA_INTEGRATOR, "ALARM_READ", "DEVICE_CONTROL", ...M2_INTEGRATE, ...M3_INTEGRATOR, ...M4_INTEGRATOR, ...M6_ANALYST];
export const OPERATOR_PERMISSIONS = [...M5_DASH_WRITE, "DEVICE_CONTROL", "ALARM_READ", ...M2_OPERATE, ...M3_OPERATOR, ...M4_OPERATOR, ...M6_ANALYST];
export const VIEWER_PERMISSIONS = [...M5_DASH_READ, "ALARM_READ", ...M2_READ, ...M6_VIEWER];
export const ANALYST_PERMISSIONS = [...M5_DASH_WRITE, "ALARM_READ", "TS_EXPORT", ...M2_READ, ...M3_ANALYST, ...M4_ANALYST, ...M5_ANALYST, "ANALYTICS_RUN", "AI_USE", "API_TOKEN_ISSUE", "ENE_READ"];
