/** 기본 역할 권한(spec/IAM-identity.md Permission 목록 중 M1·M2 화면이 쓰는 것). 가짜 gateway와 화면 렌더 도우미가 함께 쓴다 */
const M2_READ = ["DEV_READ", "TS_READ"];
const M2_OPERATE = [...M2_READ, "DEV_PLACE", "SRC_READ", "SCRIPT_READ", "INGEST_READ", "TS_EXPORT"];
const M2_INTEGRATE = [...M2_OPERATE, "DEV_ADMIN", "SRC_ADMIN", "SCRIPT_WRITE", "INGEST_PAYLOAD_READ", "INGEST_REPROCESS"];
export const ADMIN_PERMISSIONS = ["IAM_MANAGE", "AUDIT_READ", "OPS_MANAGE", "ALARM_READ", "DEVICE_CONTROL", "SCRIPT_FORCE_DEPLOY", ...M2_INTEGRATE];
export const INTEGRATOR_PERMISSIONS = ["ALARM_READ", "DEVICE_CONTROL", ...M2_INTEGRATE];
export const OPERATOR_PERMISSIONS = ["DEVICE_CONTROL", "ALARM_READ", "ALARM_HANDLE", ...M2_OPERATE];
export const VIEWER_PERMISSIONS = ["ALARM_READ", ...M2_READ];
export const ANALYST_PERMISSIONS = ["ALARM_READ", "TS_EXPORT", ...M2_READ];
