/**
 * DEV-12.01 조직 달력 모델(UI-DEV-14): 입력 검증, 월·주·목록 범위, 칸 배치, 자동 일정 수정 규칙.
 */
import { describe, expect, it } from "vitest";
import { addDays, calendarWeeks, checkEvent, defaultAffects, eventPatch, eventsOn, isAutoGenerated, monthStart, shiftAnchor, shiftMonth, sortedEvents, viewRange, weekStart } from "../calendar";

const ev = (id: string, startsOn: string, endsOn: string, extra: Record<string, unknown> = {}) => ({ id, title: id, type: "EVENT", startsOn, endsOn, origin: "MANUAL", affectsMode: "NONE", scopeSpaceIds: [], version: 1, ...extra });

describe("TC-DEV-297 입력 검증", () => {
  const ok = { title: "축제", type: "EVENT", startsOn: "2026-10-21", endsOn: "2026-10-22" };
  it("시작 ≤ 종료, 최대 366일, 제목·유형·날짜 필수, 시각은 둘 다", () => {
    expect(checkEvent(ok)).toEqual({});
    expect(checkEvent({ ...ok, endsOn: "2026-10-20" })).toEqual({ endsOn: "startAfterEnd" });
    expect(checkEvent({ ...ok, startsOn: "2026-01-01", endsOn: "2027-01-01" })).toEqual({});
    expect(checkEvent({ ...ok, startsOn: "2026-01-01", endsOn: "2027-01-02" })).toEqual({ endsOn: "tooLong366" });
    expect(checkEvent({ title: " ", type: "X", startsOn: "", endsOn: "bad" })).toEqual({ title: "required", type: "required", startsOn: "required", endsOn: "required" });
    expect(checkEvent({ ...ok, title: "가".repeat(151) })).toEqual({ title: "tooLong" });
    expect(checkEvent({ ...ok, startTime: "09:00" })).toEqual({ endTime: "timePair" });
    expect(checkEvent({ ...ok, endsOn: ok.startsOn, startTime: "10:00", endTime: "09:00" })).toEqual({ endTime: "timeOrder" });
  });

  it("유형별 기본 운영 모드 영향(core CalendarModels와 같음)", () => {
    expect(["HOLIDAY", "CLOSURE", "VACATION", "EXAM"].map(defaultAffects)).toEqual(["HOLIDAY", "HOLIDAY", "UNOCCUPIED", "NONE"]);
  });
});

describe("보기 범위와 칸", () => {
  it("월요일 시작 주, 월 보기는 앞뒤 주 포함, 주·목록 범위, 이동", () => {
    expect(weekStart("2026-10-04")).toBe("2026-09-28");
    expect(weekStart("2026-10-05")).toBe("2026-10-05");
    expect(viewRange("month", "2026-10-15")).toEqual({ from: "2026-09-28", to: "2026-11-01" });
    expect(viewRange("week", "2026-10-09")).toEqual({ from: "2026-10-05", to: "2026-10-11" });
    expect(viewRange("list", "2026-02-10")).toEqual({ from: "2026-02-01", to: "2026-02-28" });
    expect(shiftMonth("2026-12-15", 1)).toBe("2027-01-01");
    expect(shiftMonth("2026-01-15", -1)).toBe("2025-12-01");
    expect(shiftAnchor("week", "2026-10-09", -1)).toBe("2026-09-28");
    expect(shiftAnchor("month", "2026-10-09", 1)).toBe("2026-11-01");
    expect(monthStart("2026-10-09")).toBe("2026-10-01");
    expect(addDays("2026-02-28", 1)).toBe("2026-03-01");
  });

  it("월 보기 5주 × 7칸, 여러 날 일정은 해당 칸마다, 오늘·이번 달 표시", () => {
    const events = [ev("exam", "2026-10-12", "2026-10-17"), ev("holiday", "2026-10-03", "2026-10-03")];
    const weeks = calendarWeeks("month", "2026-10-01", events, "2026-10-04");
    expect(weeks).toHaveLength(5);
    expect(weeks.every((w) => w.length === 7)).toBe(true);
    const cells = weeks.flat();
    expect(cells.filter((c) => c.events.some((e) => e.id === "exam")).map((c) => c.date)).toEqual(["2026-10-12", "2026-10-13", "2026-10-14", "2026-10-15", "2026-10-16", "2026-10-17"]);
    expect(cells.find((c) => c.date === "2026-09-28")!.inMonth).toBe(false);
    expect(cells.find((c) => c.date === "2026-10-04")!.today).toBe(true);
    const week = calendarWeeks("week", "2026-10-09", events, "x");
    expect(week).toHaveLength(1);
    expect(week[0].every((c) => c.inMonth)).toBe(true);
    expect(calendarWeeks("list", "2026-10-01", [], "x")).toHaveLength(5);
    expect(eventsOn(events, "2026-10-18")).toEqual([]);
    expect(sortedEvents([ev("b", "2026-10-03", "2026-10-03"), ev("a", "2026-10-03", "2026-10-04"), ev("c", "2026-10-01", "2026-10-01")]).map((e) => e.id)).toEqual(["c", "a", "b"]);
  });
});

describe("API-DEV-102 수정 본문", () => {
  it("수동 일정은 바뀐 키만 + baseVersion, 자동 일정은 영향만", () => {
    const manual = ev("1", "2026-10-21", "2026-10-22", { title: "축제", scopeSpaceIds: ["1"], version: 3 });
    const input = { title: "축제", type: "EVENT", startsOn: "2026-10-21", endsOn: "2026-10-23", startTime: "09:00", endTime: "18:00", affectsMode: "UNOCCUPIED", scopeSpaceIds: ["2"] };
    expect(eventPatch(manual, input)).toEqual({ endsOn: "2026-10-23", startTime: "09:00", endTime: "18:00", affectsMode: "UNOCCUPIED", scopeSpaceIds: ["2"], baseVersion: 3 });
    expect(eventPatch(manual, { ...input, title: " 새 이름 ", type: "EXAM", startsOn: "2026-10-20", endsOn: "2026-10-22", startTime: "", endTime: "", affectsMode: "NONE", scopeSpaceIds: ["1"] })).toEqual({ title: "새 이름", type: "EXAM", startsOn: "2026-10-20", baseVersion: 3 });
    const auto = ev("2", "2026-10-03", "2026-10-03", { origin: "HOLIDAY_API", affectsMode: "HOLIDAY" });
    expect(isAutoGenerated(auto)).toBe(true);
    expect(eventPatch(auto, { ...input, affectsMode: "NONE" })).toEqual({ affectsMode: "NONE", baseVersion: 1 });
    expect(eventPatch(auto, { ...input, affectsMode: "HOLIDAY" })).toEqual({ baseVersion: 1 });
  });
});
