/**
 * 조직 달력 화면 부품(UI-DEV-14, DEV-12.01): 월·주·목록 보기, 유형별 색 + 출처 기호(수동 ✎·공휴일 ★·iCal ⇩),
 * 범위(사이트·공간) 필터, [일정 추가]·수정 대화상자(제목, 유형, 기간, 시간(선택), 범위, 운영 모드 영향).
 * 일정 등록·수정은 DEV_PLACE(OPERATOR+), 자동 일정은 운영 모드 영향만 바꾼다. 외부 달력 연결(I+)은 외부 맥락 화면으로 보낸다.
 */
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Form, Link } from "react-router";
import { SpaceScopePicker, SpaceSelect } from "~/components/space-picker";
import { Alert, Button, ButtonLink, Card, CsrfField, Dialog, EmptyState, SelectField, TextField, cx } from "~/components/ui";
import type { SpaceNode } from "~/lib/spaces";
import { AFFECTS_MODES, EVENT_TYPES, ORIGIN_ICON, TYPE_CLASS, calendarWeeks, checkEvent, defaultAffects, isAutoGenerated, sortedEvents, type CalendarEvent, type CalendarView as ViewKind } from "../model/calendar";

export interface CalendarResult {
  intent?: string;
  ok?: boolean;
  error?: { code: string; message?: string };
  fieldErrors?: Record<string, string>;
}

const WEEKDAYS = [0, 1, 2, 3, 4, 5, 6];

export function CalendarToolbar({ view, anchor, today, spaceId, spaces, hrefFor, canWrite, onAdd }: { view: ViewKind; anchor: string; today: string; spaceId: string; spaces: SpaceNode[]; hrefFor: (p: { view?: ViewKind; anchor?: string; spaceId?: string; shift?: number }) => string; canWrite: boolean; onAdd: () => void }) {
  const { t, i18n } = useTranslation();
  const label = new Intl.DateTimeFormat(i18n.language === "en" ? "en-US" : i18n.language, { year: "numeric", month: "long", timeZone: "UTC" }).format(new Date(`${anchor}T00:00:00Z`));
  return (
    <div className="mb-3 flex flex-wrap items-end gap-2">
      <strong className="text-[15px]" aria-live="polite">
        {label}
      </strong>
      <nav aria-label={t("calendar.nav")} className="flex gap-1">
        <Link className="rounded border border-line px-2 py-1 text-[13px]" to={hrefFor({ shift: -1 })} aria-label={t("calendar.prev")}>
          ◀
        </Link>
        <Link className="rounded border border-line px-2 py-1 text-[13px]" to={hrefFor({ anchor: today })}>
          {t("calendar.today")}
        </Link>
        <Link className="rounded border border-line px-2 py-1 text-[13px]" to={hrefFor({ shift: 1 })} aria-label={t("calendar.next")}>
          ▶
        </Link>
      </nav>
      <nav aria-label={t("calendar.viewLabel")} className="flex gap-1">
        {(["month", "week", "list"] as const).map((v) => (
          <Link key={v} to={hrefFor({ view: v })} aria-current={v === view ? "page" : undefined} className={cx("rounded border px-2 py-1 text-[13px]", v === view ? "border-accent bg-accent-soft font-semibold" : "border-line")}>
            {t(`calendar.view.${v}`)}
          </Link>
        ))}
      </nav>
      <Form method="get" className="flex items-end gap-1">
        <input type="hidden" name="view" value={view} />
        <input type="hidden" name="date" value={anchor} />
        <SpaceSelect spaces={spaces} label={t("calendar.scope")} emptyLabel={t("calendar.allScope")} name="spaceId" defaultValue={spaceId} />
        <Button type="submit">{t("calendar.applyScope")}</Button>
      </Form>
      <div className="ml-auto flex gap-2">
        {canWrite && (
          <Button variant="primary" onClick={onAdd}>
            {t("calendar.add")}
          </Button>
        )}
      </div>
    </div>
  );
}

function EventChip({ event, onOpen }: { event: CalendarEvent; onOpen: (e: CalendarEvent) => void }) {
  const { t } = useTranslation();
  return (
    <button
      type="button"
      data-event={event.id}
      onClick={() => onOpen(event)}
      className={cx("block w-full truncate rounded border px-1 text-left text-[11.5px]", TYPE_CLASS[event.type] ?? TYPE_CLASS.OTHER)}
      title={`${event.title} (${t(`calendar.type.${event.type}`, { defaultValue: event.type })})`}
    >
      <span aria-label={t(`calendar.origin.${event.origin}`, { defaultValue: event.origin })}>{ORIGIN_ICON[event.origin] ?? "•"}</span> {event.title}
      <span className="sr-only">{` (${t(`calendar.type.${event.type}`, { defaultValue: event.type })})`}</span>
      {event.originDeleted && <span className="ml-1">{t("calendar.originDeleted")}</span>}
    </button>
  );
}

export function CalendarGrid({ view, anchor, events, today, onOpen }: { view: ViewKind; anchor: string; events: CalendarEvent[]; today: string; onOpen: (e: CalendarEvent) => void }) {
  const { t } = useTranslation();
  if (view === "list") {
    const sorted = sortedEvents(events);
    if (sorted.length === 0) return <EmptyState title={t("calendar.empty")} />;
    return (
      <ul className="flex flex-col gap-1" aria-label={t("calendar.listLabel")}>
        {sorted.map((e) => (
          <li key={e.id} className="flex flex-wrap items-center gap-2 text-[13px]">
            <span className="w-48 shrink-0 font-mono text-[12px] text-muted">{e.startsOn === e.endsOn ? e.startsOn : `${e.startsOn} ~ ${e.endsOn}`}</span>
            <span className="min-w-0 flex-1">
              <EventChip event={e} onOpen={onOpen} />
            </span>
          </li>
        ))}
      </ul>
    );
  }
  const weeks = calendarWeeks(view, anchor, events, today);
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[640px] table-fixed border-collapse text-[12.5px]" aria-label={t("calendar.gridLabel")}>
        <thead>
          <tr>
            {WEEKDAYS.map((d) => (
              <th key={d} scope="col" className="border border-line px-1 py-1 text-muted">
                {t(`calendar.weekday.${d}`)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {weeks.map((week) => (
            <tr key={week[0].date}>
              {week.map((cell) => (
                <td key={cell.date} data-date={cell.date} className={cx("h-20 border border-line p-1 align-top", !cell.inMonth && "bg-bg text-muted", cell.today && "outline outline-2 -outline-offset-2 outline-accent")}>
                  <div className="mb-0.5 text-right font-mono text-[11px]">{Number(cell.date.slice(8))}</div>
                  <div className="flex flex-col gap-0.5">
                    {cell.events.map((e) => (
                      <EventChip key={e.id} event={e} onOpen={onOpen} />
                    ))}
                  </div>
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function EventDialog({ event, defaultDate, spaces, canWrite, result, onClose }: { event: CalendarEvent | null; defaultDate: string; spaces: SpaceNode[]; canWrite: boolean; result?: CalendarResult; onClose: () => void }) {
  const { t } = useTranslation();
  const auto = event ? isAutoGenerated(event) : false;
  const [title, setTitle] = useState(event?.title ?? "");
  const [type, setType] = useState(event?.type ?? "EVENT");
  const [startsOn, setStartsOn] = useState(event?.startsOn ?? defaultDate);
  const [endsOn, setEndsOn] = useState(event?.endsOn ?? defaultDate);
  const [startTime, setStartTime] = useState(event?.startTime ?? "");
  const [endTime, setEndTime] = useState(event?.endTime ?? "");
  const [affects, setAffects] = useState(event?.affectsMode ?? defaultAffects(type));
  const [touchedAffects, setTouchedAffects] = useState(Boolean(event));
  const errors = auto ? {} : checkEvent({ title, type, startsOn, endsOn, startTime, endTime });
  const server = result?.fieldErrors ?? {};
  const err = (k: string) => {
    const code = errors[k] ?? server[k];
    return code ? t(`calendar.validation.${code}`, { defaultValue: code }) : undefined;
  };
  const readOnly = !canWrite;
  const formId = "calendar-event-form";
  return (
    <Dialog
      title={event ? (readOnly ? event.title : t("calendar.edit")) : t("calendar.add")}
      open
      onClose={onClose}
      footer={
        canWrite && (
          <>
            {event && !auto && (
              <Form method="post">
                <CsrfField />
                <input type="hidden" name="intent" value="delete" />
                <input type="hidden" name="id" value={event.id} />
                <Button type="submit" variant="danger">
                  {t("calendar.delete")}
                </Button>
              </Form>
            )}
            <Button type="submit" form={formId} variant="primary" disabled={Object.keys(errors).length > 0}>
              {t("common.save")}
            </Button>
          </>
        )
      }
    >
      {auto && <Alert tone="info">{t("calendar.autoNote", { origin: t(`calendar.origin.${event!.origin}`, { defaultValue: event!.origin }) })}</Alert>}
      {event?.originDeleted && <Alert tone="warning">{t("calendar.originDeletedNote")}</Alert>}
      {result?.error && <Alert tone="danger">{t(`errors.${result.error.code}`, { defaultValue: result.error.message || t("errors.UNKNOWN") })}</Alert>}
      <Form method="post" id={formId} className="flex flex-col gap-2">
        <CsrfField />
        <input type="hidden" name="intent" value={event ? "update" : "create"} />
        {event && <input type="hidden" name="id" value={event.id} />}
        <TextField label={t("calendar.field.title")} name="title" value={title} onChange={(e) => setTitle(e.target.value)} disabled={auto || readOnly} error={err("title")} maxLength={150} />
        <SelectField
          label={t("calendar.field.type")}
          name="type"
          value={type}
          disabled={auto || readOnly}
          onChange={(e) => {
            setType(e.target.value);
            if (!touchedAffects) setAffects(defaultAffects(e.target.value));
          }}
        >
          {EVENT_TYPES.map((x) => (
            <option key={x} value={x}>
              {t(`calendar.type.${x}`)}
            </option>
          ))}
        </SelectField>
        <div className="grid grid-cols-2 gap-2">
          <TextField label={t("calendar.field.startsOn")} type="date" name="startsOn" value={startsOn} onChange={(e) => setStartsOn(e.target.value)} disabled={auto || readOnly} error={err("startsOn")} />
          <TextField label={t("calendar.field.endsOn")} type="date" name="endsOn" value={endsOn} onChange={(e) => setEndsOn(e.target.value)} disabled={auto || readOnly} error={err("endsOn")} />
          <TextField label={t("calendar.field.startTime")} type="time" name="startTime" value={startTime} onChange={(e) => setStartTime(e.target.value)} disabled={auto || readOnly} />
          <TextField label={t("calendar.field.endTime")} type="time" name="endTime" value={endTime} onChange={(e) => setEndTime(e.target.value)} disabled={auto || readOnly} error={err("endTime")} />
        </div>
        {!auto && !readOnly && <SpaceScopePicker spaces={spaces} name="scopeSpaceIds" defaultValue={event?.scopeSpaceIds ?? []} label={t("calendar.field.scope")} />}
        <SelectField
          label={t("calendar.field.affectsMode")}
          name="affectsMode"
          value={affects}
          disabled={readOnly}
          onChange={(e) => {
            setAffects(e.target.value);
            setTouchedAffects(true);
          }}
        >
          {AFFECTS_MODES.map((m) => (
            <option key={m} value={m}>
              {t(`calendar.affects.${m}`)}
            </option>
          ))}
        </SelectField>
      </Form>
    </Dialog>
  );
}

export function ExternalCalendarLink({ canConnect }: { canConnect: boolean }) {
  const { t } = useTranslation();
  if (!canConnect) return null;
  return (
    <Card>
      <p className="text-[13px]">
        {t("calendar.externalNote")} <ButtonLink to="/sources/context">{t("calendar.externalLink")}</ButtonLink>
      </p>
    </Card>
  );
}
